const vehicles = [
  {
    id: '1',
    license_plate: 'ABC-123',
    economic_number: '123',
    vim: '123456',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2021,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Rojo',
  },
  {
    id: '2',
    license_plate: 'DEF-456',
    economic_number: '456',
    vim: '456789',
    brand: 'Honda',
    model: 'Civic',
    year: 2020,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Azul',
  },
  {
    id: '3',
    license_plate: 'DEF-456',
    economic_number: '456',
    vim: '456789',
    brand: 'Honda',
    model: 'Civic',
    year: 2020,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Azul',
  },
  {
    id: '1',
    license_plate: 'ABC-123',
    economic_number: '123',
    vim: '123456',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2021,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Rojo',
  },
  {
    id: '2',
    license_plate: 'DEF-456',
    economic_number: '456',
    vim: '456789',
    brand: 'Honda',
    model: 'Civic',
    year: 2020,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Azul',
  },
  {
    id: '3',
    license_plate: 'DEF-456',
    economic_number: '456',
    vim: '456789',
    brand: 'Honda',
    model: 'Civic',
    year: 2020,
    insurance: 'Seguro de daños',
    insurance_number: '123456',
    seats: 5,
    color: 'Azul',
  },
];